# Generated by Django 2.2.11 on 2020-03-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200322_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='Роман', max_length=200),
        ),
    ]
